project_structure:
    contracts: ../hardhat/contracts
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.4.2
compiler:
    solc:
        remappings:
            - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.2'